export const GET_AUTH_TOKEN_SIMPLE = 'GET_AUTH_TOKEN_SIMPLE';
export const LOGIN_SUCCESS         = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE         = 'LOGIN_FAILURE';

export const TODO_GET_ITEMS         = 'TODO_GET_ITEMS';
export const TODO_GET_ITEMS_SUCCESS = 'TODO_GET_ITEMS_SUCCESS';

export const TODO_POST_ITEM         = 'TODO_POST_ITEM';
export const TODO_POST_ITEM_SUCCESS = 'TODO_POST_ITEM_SUCCESS';
